# Generated by Django 6.0 on 2025-12-05 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('hero', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('cover', models.ImageField(upload_to='covers/')),
                ('review', models.TextField()),
            ],
        ),
    ]
