# Generated by Django 6.0 on 2025-12-05 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='hero',
        ),
        migrations.AddField(
            model_name='movie',
            name='cast',
            field=models.TextField(blank=True, help_text='Enter actors names separated by commas', null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.CharField(default='Not Available', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.CharField(default='Unknown', max_length=50),
            preserve_default=False,
        ),
    ]
