# Generated by Django 6.0 on 2025-12-18 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userprofile',
        ),
    ]
