# Generated by Django 6.0 on 2025-12-29 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_person_remove_movie_actors_remove_movie_cast_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('actor', 'Actor'), ('director', 'Director'), ('producer', 'Producer'), ('writer', 'Writer')], max_length=20)),
                ('character_name', models.CharField(blank=True, max_length=100, null=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='movies.movie')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.person')),
            ],
            options={
                'unique_together': {('movie', 'person', 'role')},
            },
        ),
    ]
